import { StyleSheet } from 'react-native';

import type { AppTheme } from '@/hooks/app-theme';

export function createCreateEventStyles(theme: AppTheme, bottomInset = 0) {
  const { colors, fontFamily, spacing, typography } = theme;

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.background.surface,
    },
    progress: {
      height: 60,
      gap: 10,
      paddingTop: 6,
      paddingHorizontal: spacing.x6,
      backgroundColor: colors.background.surface,
    },
    progressLabels: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    progressCount: {
      ...typography.labelSmall,
      letterSpacing: 0,
      color: colors.text.primary,
    },
    progressName: {
      ...typography.caption,
      color: colors.text.secondary,
    },
    progressSegments: {
      flexDirection: 'row',
      gap: 6,
    },
    progressSegment: {
      flex: 1,
      height: spacing.x1,
      borderRadius: 2,
      backgroundColor: colors.border.default,
    },
    progressSegmentActive: {
      backgroundColor: colors.background.brand,
    },
    keyboardView: {
      flex: 1,
    },
    content: {
      flexGrow: 1,
      paddingHorizontal: spacing.x6,
      paddingTop: spacing.x4,
      paddingBottom: spacing.x6,
    },
    contentCompact: {
      paddingTop: spacing.x3,
    },
    intro: {
      gap: spacing.x1,
      marginBottom: 18,
    },
    title: {
      ...typography.heading3,
      color: colors.text.primary,
    },
    subtitle: {
      ...typography.bodySmall,
      color: colors.text.secondary,
    },
    optionsList: {
      gap: spacing.x3,
    },
    selectionCard: {
      minHeight: spacing.x20,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.x3,
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x4,
      backgroundColor: colors.background.surface,
    },
    selectionCardSelected: {
      borderWidth: 2,
      borderColor: colors.border.brand,
      backgroundColor: colors.background.subtle,
      paddingHorizontal: 13,
    },
    selectionIcon: {
      width: spacing.x12,
      height: spacing.x12,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 14,
      backgroundColor: colors.background.accent,
    },
    selectionIconSelected: {
      backgroundColor: colors.background.brand,
    },
    selectionCopy: {
      flex: 1,
      gap: 2,
    },
    selectionLabel: {
      ...typography.labelLarge,
      color: colors.text.primary,
    },
    selectionHint: {
      ...typography.caption,
      color: colors.text.secondary,
    },
    radio: {
      width: 22,
      height: 22,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: colors.border.default,
      borderRadius: 11,
    },
    radioSelected: {
      borderColor: colors.border.brand,
      backgroundColor: colors.background.brand,
    },
    radioDot: {
      width: spacing.x2,
      height: spacing.x2,
      borderRadius: spacing.x1,
      backgroundColor: colors.text.onBrand,
    },
    totalCard: {
      minHeight: spacing.x16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.x4,
      borderRadius: spacing.x4,
      backgroundColor: colors.background.subtle,
    },
    totalCopy: { gap: 2 },
    totalLabel: {
      ...typography.labelLarge,
      color: colors.text.primary,
    },
    totalHint: {
      ...typography.caption,
      color: colors.text.secondary,
    },
    totalValue: {
      ...typography.heading2,
      color: colors.background.brand,
    },
    counters: {
      gap: 10,
      marginTop: spacing.x4,
    },
    counterRow: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: spacing.x4,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x4,
      backgroundColor: colors.background.surface,
    },
    counterCopy: { flex: 1, gap: 2 },
    counterLabel: {
      ...typography.labelLarge,
      color: colors.text.primary,
    },
    counterHint: {
      ...typography.caption,
      color: colors.text.secondary,
    },
    stepper: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.x2,
    },
    stepperButton: {
      width: spacing.x8,
      height: spacing.x8,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 10,
      backgroundColor: colors.background.brand,
    },
    stepperButtonDisabled: {
      backgroundColor: colors.background.subtle,
    },
    stepperValue: {
      ...typography.labelLarge,
      minWidth: 20,
      color: colors.text.primary,
      textAlign: 'center',
    },
    infoBox: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.x2,
      marginTop: spacing.x4,
      padding: spacing.x3,
      borderRadius: spacing.x3,
      backgroundColor: colors.background.subtle,
    },
    infoText: {
      ...typography.caption,
      flex: 1,
      color: colors.text.secondary,
    },
    fields: { gap: spacing.x3 },
    fieldGroup: { gap: spacing.x2 },
    fieldLabel: {
      ...typography.labelSmall,
      letterSpacing: 0,
      color: colors.text.primary,
    },
    fieldLabelRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    optional: {
      ...typography.caption,
      color: colors.text.muted,
    },
    input: {
      ...typography.bodySmall,
      height: 50,
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: 14,
      color: colors.text.primary,
      backgroundColor: colors.background.surface,
      fontFamily: fontFamily.regular,
    },
    multilineInput: {
      height: 54,
      paddingTop: 14,
      textAlignVertical: 'top',
    },
    inputError: { borderColor: colors.status.errorForeground },
    errorText: {
      ...typography.caption,
      color: colors.status.errorForeground,
    },
    dateField: {
      height: 50,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: 14,
      backgroundColor: colors.background.surface,
    },
    dateText: {
      ...typography.bodySmall,
      color: colors.text.primary,
    },
    durationRow: { flexDirection: 'row', gap: spacing.x2 },
    durationOption: {
      flex: 1,
      height: 38,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x3,
      backgroundColor: colors.background.surface,
    },
    durationOptionSelected: {
      borderWidth: 2,
      borderColor: colors.border.brand,
      backgroundColor: colors.background.subtle,
    },
    durationLabel: {
      ...typography.labelSmall,
      letterSpacing: 0,
      color: colors.text.primary,
    },
    durationLabelSelected: { color: colors.background.brand },
    customDurationRow: { position: 'relative' },
    customDurationSuffix: {
      ...typography.caption,
      position: 'absolute',
      right: 14,
      top: 15,
      color: colors.text.secondary,
    },
    customDurationHint: {
      ...typography.caption,
      marginTop: spacing.x1,
      color: colors.text.secondary,
    },
    locationRow: { flexDirection: 'row', gap: 10 },
    locationOption: {
      flex: 1,
      height: 68,
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.x1,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x3,
      backgroundColor: colors.background.surface,
    },
    locationOptionSelected: {
      borderWidth: 2,
      borderColor: colors.border.brand,
      backgroundColor: colors.background.subtle,
    },
    locationLabel: {
      ...typography.labelSmall,
      letterSpacing: 0,
      color: colors.text.primary,
    },
    locationLabelSelected: { color: colors.background.brand },
    seasonBox: {
      minHeight: 38,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.x2,
      paddingHorizontal: spacing.x3,
      borderRadius: 10,
      backgroundColor: colors.background.subtle,
    },
    seasonText: {
      ...typography.caption,
      flex: 1,
      color: colors.text.secondary,
    },
    menuOptions: { flexDirection: 'row', gap: spacing.x2 },
    menuOption: {
      flex: 1,
      height: 66,
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.x1,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x3,
      backgroundColor: colors.background.surface,
    },
    menuOptionSelected: {
      borderWidth: 2,
      borderColor: colors.border.brand,
      backgroundColor: colors.background.subtle,
    },
    menuOptionLabel: {
      ...typography.caption,
      fontFamily: fontFamily.semiBold,
      color: colors.text.primary,
      textAlign: 'center',
    },
    menuOptionLabelSelected: { color: colors.background.brand },
    menuDescription: {
      minHeight: spacing.x12,
      justifyContent: 'center',
      marginTop: spacing.x2,
      paddingHorizontal: 10,
      borderRadius: 10,
      backgroundColor: colors.background.subtle,
    },
    menuDescriptionText: {
      ...typography.caption,
      color: colors.text.secondary,
    },
    drinksSection: { marginTop: 14 },
    chips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.x2,
      marginTop: 7,
    },
    chip: {
      height: spacing.x8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 11,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x3,
      backgroundColor: colors.background.surface,
    },
    chipSelected: {
      borderWidth: 2,
      borderColor: colors.border.brand,
      backgroundColor: colors.background.subtle,
      paddingHorizontal: 10,
    },
    chipLabel: {
      ...typography.labelSmall,
      letterSpacing: 0,
      color: colors.text.primary,
    },
    chipLabelSelected: { color: colors.background.brand },
    drinksHint: {
      ...typography.caption,
      marginTop: spacing.x2,
      color: colors.text.secondary,
    },
    reviewCards: { gap: spacing.x2 },
    reviewCard: {
      minHeight: 62,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: spacing.x3,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: 14,
      backgroundColor: colors.background.surface,
    },
    reviewIcon: {
      width: spacing.x10,
      height: spacing.x10,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: spacing.x3,
      backgroundColor: colors.background.subtle,
    },
    reviewCopy: { flex: 1, gap: 2 },
    reviewTitle: {
      ...typography.bodySmall,
      fontFamily: fontFamily.semiBold,
      color: colors.text.primary,
    },
    reviewHint: {
      ...typography.caption,
      color: colors.text.secondary,
    },
    change: {
      ...typography.labelSmall,
      letterSpacing: 0,
      color: colors.background.brand,
    },
    reviewFields: { gap: spacing.x3, marginTop: 14 },
    footer: {
      paddingHorizontal: spacing.x6,
      paddingTop: spacing.x3,
      paddingBottom: Math.max(bottomInset, spacing.x3),
      backgroundColor: colors.background.surface,
    },
    headerButton: {
      width: spacing.x10,
      height: spacing.x10,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: spacing.x3,
    },
    pressed: { opacity: 0.72 },
  });
}
