import { StyleSheet } from 'react-native';

import type { AppTheme } from '@/hooks/app-theme';

export function createInvitationStyles(theme: AppTheme) {
  const { colors, spacing, typography } = theme;

  return StyleSheet.create({
    screen: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: colors.background.canvas,
    },
    page: {
      width: '100%',
      maxWidth: 520,
      flex: 1,
      paddingHorizontal: spacing.x5,
      paddingVertical: spacing.x4,
    },
    homeAction: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.x2,
      minHeight: spacing.x10,
      marginBottom: spacing.x3,
      paddingHorizontal: spacing.x3,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x5,
      backgroundColor: colors.background.surface,
    },
    homeActionPressed: {
      opacity: 0.68,
    },
    homeActionText: {
      ...typography.labelSmall,
      color: colors.text.primary,
    },
    content: {
      width: '100%',
      gap: spacing.x5,
    },
    brand: {
      ...typography.overline,
      color: colors.text.brand,
      textAlign: 'center',
    },
    badge: {
      alignSelf: 'center',
      paddingHorizontal: spacing.x4,
      paddingVertical: spacing.x2,
      borderRadius: spacing.x5,
      backgroundColor: colors.background.accentSubtle,
    },
    badgeText: {
      ...typography.overline,
      color: colors.background.accent,
    },
    heroTitle: {
      ...typography.heading2,
      color: colors.text.primary,
      textAlign: 'center',
    },
    invitedBy: {
      ...typography.bodyMedium,
      marginTop: -spacing.x4,
      color: colors.text.secondary,
      textAlign: 'center',
    },
    eventCard: {
      gap: spacing.x3,
      padding: spacing.x4,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x4,
      backgroundColor: colors.background.surface,
    },
    eventDate: { ...typography.titleMedium, color: colors.text.primary },
    locationRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.x2 },
    location: { ...typography.bodySmall, flex: 1, color: colors.text.secondary },
    infoCard: {
      gap: spacing.x1,
      padding: spacing.x4,
      borderRadius: spacing.x4,
      backgroundColor: colors.background.subtle,
    },
    infoTitle: { ...typography.labelLarge, color: colors.text.brand },
    infoBody: { ...typography.bodySmall, color: colors.text.secondary },
    privacy: {
      ...typography.caption,
      color: colors.text.muted,
      textAlign: 'center',
    },
    centeredState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.x4,
    },
    stateTitle: { ...typography.heading3, color: colors.text.primary, textAlign: 'center' },
    stateMessage: {
      ...typography.bodyMedium,
      color: colors.text.secondary,
      textAlign: 'center',
    },
    warningIcon: {
      width: spacing.x24,
      height: spacing.x24,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: spacing.x12,
      backgroundColor: colors.status.warningBackground,
    },
    warningCard: {
      width: '100%',
      gap: spacing.x2,
      marginTop: spacing.x8,
      padding: spacing.x4,
      borderRadius: spacing.x4,
      backgroundColor: colors.status.warningBackground,
    },
    warningTitle: { ...typography.labelLarge, color: colors.status.warningForeground },
    warningBody: { ...typography.bodySmall, color: colors.text.secondary },
    formEyebrow: {
      ...typography.overline,
      color: colors.text.brand,
      textAlign: 'center',
    },
    formTitle: {
      ...typography.heading3,
      marginTop: -spacing.x3,
      color: colors.text.primary,
      textAlign: 'center',
    },
    sectionTitle: { ...typography.labelLarge, color: colors.text.primary },
    counterCard: {
      flexDirection: 'row',
      gap: spacing.x3,
      marginTop: -spacing.x3,
      padding: spacing.x3,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x4,
      backgroundColor: colors.background.surface,
    },
    counter: { flex: 1, gap: spacing.x2 },
    counterLabel: { ...typography.bodySmall, color: colors.text.secondary },
    counterControls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    counterButton: {
      width: spacing.x8,
      height: spacing.x8,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: spacing.x4,
      backgroundColor: colors.background.subtle,
    },
    counterButtonText: { ...typography.titleMedium, color: colors.text.brand },
    counterValue: { ...typography.titleMedium, minWidth: spacing.x6, color: colors.text.primary, textAlign: 'center' },
    validationError: { ...typography.caption, marginTop: -spacing.x4, color: colors.status.errorForeground },
    statusOptions: { flexDirection: 'row', gap: spacing.x2, marginTop: -spacing.x3 },
    statusOption: {
      minHeight: spacing.x12,
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.x2,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x4,
      backgroundColor: colors.background.surface,
    },
    statusOptionSelected: { borderColor: colors.background.accent, backgroundColor: colors.background.accentSubtle },
    statusOptionText: { ...typography.labelSmall, color: colors.text.secondary, textAlign: 'center' },
    statusOptionTextSelected: { color: colors.background.accent },
    summaryCard: { padding: spacing.x4, borderRadius: spacing.x4, backgroundColor: colors.background.subtle },
    summaryText: { ...typography.labelLarge, color: colors.text.brand, textAlign: 'center' },
    submitError: { ...typography.bodySmall, color: colors.status.errorForeground, textAlign: 'center' },
    successContent: { flex: 1, justifyContent: 'center' },
    successIcon: {
      width: spacing.x24,
      height: spacing.x24,
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: spacing.x12,
      backgroundColor: colors.status.successBackground,
    },
    responseCard: {
      gap: spacing.x2,
      padding: spacing.x4,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x4,
      backgroundColor: colors.background.surface,
    },
    responseName: { ...typography.titleMedium, color: colors.text.primary },
    responsePeople: { ...typography.bodySmall, color: colors.text.secondary },
    responseStatus: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.x1,
      paddingHorizontal: spacing.x3,
      paddingVertical: spacing.x1,
      borderRadius: spacing.x4,
      backgroundColor: colors.status.successBackground,
    },
    responseStatusText: { ...typography.labelSmall, color: colors.status.successForeground },
  });
}
