import type { TranslationSchema } from '@/localization/types';

export const en: TranslationSchema = {
  common: {
    cancel: 'Cancel',
    dismiss: 'Dismiss message',
    socialAuth: {
      continueWithGoogle: 'Continue with Google',
      googleErrorTitle: 'Unable to sign in with Google',
      errors: {
        providerDisabled: 'Google sign-in is currently unavailable. Please try again later.',
        network: 'Unable to connect. Check your internet connection and try again.',
        invalidCallback: 'Unable to complete sign-in. Please try again.',
        unknown: 'An error occurred while signing in. Please try again.',
      },
    },
  },
  welcome: {
    eyebrow: 'A STRESS-FREE PARTY',
    title: 'Plan your party\nin just a few minutes',
    subtitle:
      "We'll calculate the food, drinks, and shopping — all you need to do is check things off.",
    createAccount: 'Create account',
    existingAccount: 'Already have an account?',
    login: 'Sign in',
    legal: 'By continuing, you agree to the Terms and Privacy Policy',
  },
  invitation: {
    brand: 'PARTY PLANER',
    badge: 'YOU ARE INVITED',
    invitedBy: 'Invited by {name}',
    eventFallback: 'Event',
    browserNoteTitle: 'No app installation needed',
    browserNoteBody: 'You can respond directly in your browser.',
    respond: 'Respond to invitation',
    privacy: 'The organizer will only see the information you enter.',
    formEyebrow: 'INVITATION RESPONSE',
    nameLabel: 'Your name or family name',
    namePlaceholder: 'For example, Alex',
    peopleQuestion: 'How many people are coming?',
    adults: 'Adults',
    children: 'Children',
    attendanceQuestion: 'Will you attend?',
    accepted: 'Going',
    maybe: 'Maybe',
    declined: "Can't go",
    responseSummary: '{name} · {adults} adults · {children} children',
    submit: 'Send response',
    submitting: 'Sending…',
    validationName: 'Enter your name or family name.',
    validationPartySize: 'Add at least one person.',
    submitError: 'Unable to send your response. Please try again.',
    successTitle: 'Response sent',
    successMessage: 'The organizer can now see your group’s response.',
    addGroup: 'Add another group',
    done: 'Done',
    missingTitle: 'Invitation unavailable',
    missingMessage: 'Open the complete link shared by the organizer.',
    unavailableHintTitle: 'What can you do?',
    unavailableHintMessage: 'Ask the organizer to send a new invitation link.',
    loading: 'Loading invitation…',
  },
  login: {
    back: 'Back',
    title: 'Welcome back!',
    subtitle: 'Sign in to continue planning your party.',
    emailLabel: 'Email',
    emailPlaceholder: 'name@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    showPassword: 'Show',
    hidePassword: 'Hide',
    forgotPassword: 'Forgot password?',
    login: 'Sign in',
    loginErrorTitle: 'Unable to sign in',
    loginSuccess: 'You have signed in successfully.',
    loginSuccessTitle: 'Signed in',
    loggingIn: 'Signing in…',
    or: 'or',
    noAccount: "Don't have an account?",
    createAccount: 'Create account',
    securityNote: 'Your data is protected and never shared with third parties',
    errors: {
      invalidCredentials: 'Incorrect email or password.',
      emailNotConfirmed: 'Confirm your email before signing in.',
      rateLimited: 'Too many sign-in attempts. Please try again later.',
      network: 'Unable to connect. Check your internet connection and try again.',
      unknown: 'Unable to sign in. Please try again.',
    },
    validation: {
      emailRequired: 'Enter your email',
      emailInvalid: 'Enter a valid email',
      passwordRequired: 'Enter your password',
    },
  },
  emailConfirmation: {
    back: 'Back',
    title: 'Confirm your email',
    subtitle: 'Open the email and follow the link to activate your account.',
    emailSentTo: 'Email sent to {email}',
    resend: 'Send email again',
    resending: 'Sending…',
    goToLogin: 'Go to sign in',
    resendSuccessTitle: 'Email sent',
    resendSuccessMessage: 'Check your inbox and spam folder.',
    resendErrorTitle: 'Unable to send email',
    errors: {
      invalidEmail: 'The email address is invalid.',
      network: 'Check your connection and try again.',
      rateLimited: 'Too many requests. Please try again later.',
      unknown: 'Unable to send the email. Please try again.',
    },
  },
  forgotPassword: {
    back: 'Back',
    title: 'Reset password',
    subtitle: 'Enter your email and we will send you a link to create a new password.',
    emailLabel: 'Email',
    emailPlaceholder: 'name@example.com',
    submit: 'Send reset link',
    submitting: 'Sending…',
    sentTitle: 'Check your email',
    sentMessage: 'A password reset link was sent to {email}.',
    errorTitle: 'Unable to send reset link',
    errors: {
      invalidEmail: 'Enter a valid email.',
      network: 'Check your connection and try again.',
      rateLimited: 'Too many requests. Please try again later.',
      unknown: 'Unable to send the email. Please try again.',
    },
    validation: {
      emailRequired: 'Enter your email',
      emailInvalid: 'Enter a valid email',
    },
  },
  changePassword: {
    back: 'Back',
    title: 'Change password',
    recoveryTitle: 'Create a new password',
    subtitle: 'Confirm your current password and enter a new one.',
    recoverySubtitle: 'Your new password must be at least 8 characters long.',
    currentPasswordLabel: 'Current password',
    passwordLabel: 'New password',
    confirmPasswordLabel: 'Repeat new password',
    passwordPlaceholder: 'At least 8 characters',
    showPassword: 'Show',
    hidePassword: 'Hide',
    submit: 'Save password',
    submitting: 'Saving…',
    successTitle: 'Password changed',
    successMessage: 'Your new password was saved successfully.',
    errorTitle: 'Unable to change password',
    invalidLinkTitle: 'Invalid link',
    invalidLinkMessage: 'The link has expired or has already been used.',
    goToLogin: 'Return to sign in',
    errors: {
      invalidCurrentPassword: 'The current password is incorrect.',
      network: 'Check your connection and try again.',
      rateLimited: 'Too many attempts. Please try again later.',
      samePassword: 'The new password must be different from the current one.',
      sessionMissing: 'The recovery session has expired. Request a new link.',
      unknown: 'Unable to change the password. Please try again.',
      weakPassword: 'Choose a stronger password.',
    },
    validation: {
      currentPasswordRequired: 'Enter your current password',
      passwordRequired: 'Enter a new password',
      passwordTooShort: 'Password must be at least 8 characters',
      confirmPasswordRequired: 'Repeat the new password',
      passwordMismatch: 'Passwords do not match',
    },
  },
  authCallback: {
    confirming: 'Confirming your account…',
    successTitle: 'Email confirmed',
    successMessage: 'Your account is active. You can continue planning.',
    errorTitle: 'Unable to confirm email',
    errorMessage: 'The link has expired or has already been used.',
    goToLogin: 'Go to sign in',
  },
  createAccount: {
    back: 'Back',
    title: 'Create account',
    subtitle: 'Start planning parties without the extra stress.',
    nameLabel: 'Name',
    namePlaceholder: 'Your name',
    emailLabel: 'Email',
    emailPlaceholder: 'name@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'At least 8 characters',
    showPassword: 'Show',
    hidePassword: 'Hide',
    submit: 'Create account',
    submitting: 'Creating…',
    or: 'or',
    existingAccount: 'Already have an account?',
    login: 'Sign in',
    legal: 'By registering, you agree to the Terms and Privacy Policy',
    successTitle: 'Account created',
    success: 'Registration is complete.',
    confirmationTitle: 'Confirm your email',
    confirmationMessage: 'We sent you an email with a confirmation link.',
    errorTitle: 'Unable to create account',
    errors: {
      emailAlreadyRegistered: 'An account with this email already exists.',
      invalidEmail: 'Enter a valid email.',
      weakPassword: 'Choose a stronger password.',
      signUpDisabled: 'Registration is currently unavailable.',
      rateLimited: 'Too many attempts. Please try again later.',
      network: 'Unable to connect. Check your internet connection and try again.',
      unknown: 'Unable to create account. Please try again.',
    },
    validation: {
      nameRequired: 'Enter your name',
      nameTooLong: 'Name must be 120 characters or fewer',
      emailRequired: 'Enter your email',
      emailInvalid: 'Enter a valid email',
      passwordRequired: 'Enter a password',
      passwordTooShort: 'Password must be at least 8 characters',
    },
  },
  myEvents: {
    title: 'My events',
    greeting: 'Hi, {name}! All your plans will appear here.',
    greetingWithEvents: 'Hi, {name}! Here are your events.',
    defaultName: 'Friend',
    openProfile: 'Open profile',
    emptyTitle: 'Create your first event?',
    emptyBody: "Add guests and a party format — we'll prepare the plan, shopping list, and checklist.",
    createEvent: 'Create event',
    hintTitle: 'A plan in a few minutes',
    hintBody: 'Calculations and lists will be created automatically.',
    guests: '{count} guests',
    checklistProgress: '{completed} of {total} tasks completed',
    checklistComplete: 'All ready · {completed} of {total}',
    shoppingProgress: '{purchased} of {total} items purchased',
    shoppingComplete: 'Shopping complete · {purchased} of {total}',
    shoppingEmpty: 'Fill in shopping list',
    loadError: 'Unable to load events.',
    retry: 'Try again',
    createAnother: 'Create another event',
    listView: 'List',
    calendarView: 'Calendar',
    eventsInMonth: '{count} this month',
    eventsCountOne: '{count} event',
    eventsCountFew: '{count} events',
    eventsCountMany: '{count} events',
    noEventsInMonth: 'There are no events this month.',
    previousYear: 'Previous year',
    nextYear: 'Next year',
    upcomingEvents: 'Upcoming',
    pastEvents: 'Past',
    noUpcomingEvents: 'There are no upcoming events yet.',
    noPastEvents: 'Completed and past events will appear here.',
    statuses: {
      completed: 'Completed',
      needsClosure: 'Needs completion',
      ongoing: 'Happening now',
      upcoming: 'Planned',
    },
  },
  createEvent: {
    headerTitle: 'Create event',
    back: 'Back',
    close: 'Close event creation',
    next: 'Next',
    createPlan: 'Create plan',
    creatingPlan: 'Creating plan…',
    step: 'Step {current} of {total}',
    steps: {
      eventType: 'Event type',
      guests: 'Guests',
      details: 'Details',
      menu: 'Menu & drinks',
      review: 'Review',
    },
    eventType: {
      title: 'What are we planning?',
      subtitle: 'Choose a format to help us calculate shopping more accurately.',
      birthday: 'Birthday',
      birthdayHint: 'A festive menu and drinks',
      bbq: 'BBQ / picnic',
      bbqHint: 'Grilling and relaxing outdoors',
      homeParty: 'House party',
      homePartyHint: 'A cozy indoor format',
      other: 'Other event',
      otherHint: 'Any format that fits your plans',
    },
    guests: {
      title: 'Who is coming?',
      subtitle: 'Enter the guest counts — we will calculate the total automatically.',
      inviteLaterHint: 'Later, you can share the invitation or show its QR code.',
      total: 'Total guests',
      breakdown: '{adults} adults · {children} children',
      adults: 'Adults',
      adultsHint: '18 and over',
      children: 'Children',
      childrenHint: 'Under 18',
      alcohol: 'Drink alcohol',
      alcoholHint: 'Maximum {max}',
      validationHint: 'The number of guests drinking alcohol cannot exceed the adult count.',
    },
    details: {
      title: 'When and where?',
      subtitle: 'Add the main event details.',
      name: 'Event name',
      namePlaceholder: "For example, Alina's birthday",
      date: 'Date',
      time: 'Start time',
      timePlaceholder: '18:00',
      duration: 'Duration',
      durationHours: '{value} hr',
      other: 'Other',
      customDurationHint: 'From 1 to 24 hours',
      location: 'Location',
      indoor: 'Indoors',
      outdoor: 'Outdoors',
      locationText: 'Venue',
      locationTextPlaceholder: 'For example, 10 Main Street or a venue name',
      optional: 'Optional',
      seasonHint: 'Based on the date: {season} — we will allow for more water and, if selected, ice.',
      seasons: {
        winter: 'winter',
        spring: 'spring',
        summer: 'summer',
        autumn: 'autumn',
      },
    },
    menu: {
      title: 'What will be served?',
      subtitle: 'Choose the menu format and drink categories.',
      format: 'Menu format',
      snacks: 'Snacks',
      buffet: 'Buffet',
      full: 'Full menu',
      descriptions: {
        snacks: 'Snacks: canapés, finger food, fruit, and a light dessert.',
        buffet: 'Buffet: snacks, canapés, and one main dish.',
        full: 'Full menu: starter, main course, side, and dessert.',
      },
      drinks: 'Drinks',
      beer: 'Beer',
      wine: 'Wine',
      spirits: 'Spirits',
      water: 'Water',
      juice: 'Juice',
      soda: 'Soda',
      waterHint: 'Water is always calculated, regardless of your selection.',
      supplies: 'What should be added to the plan?',
      optional: 'Optional',
      ice: 'Ice',
      plates: 'Plates',
      cups: 'Glasses',
      suppliesHint: 'Only selected items will be calculated. You can change them later.',
    },
    review: {
      title: 'Review everything',
      subtitle: 'Go back and edit any section if needed.',
      change: 'Edit',
      guestsSummary: '{total} guests',
      drinksSummary: '{menu}. {drinks}',
      suppliesSummary: 'supplies: {supplies}',
      noSupplies: 'no additional supplies',
      budget: 'Budget',
      optional: 'Optional',
      budgetPlaceholder: '8,000',
      currency: '₴',
      note: 'Note',
      notePlaceholder: 'For example, buy the cake separately',
    },
    exit: {
      title: 'Close event creation?',
      message: 'Your unsaved event details will be lost. This action cannot be undone.',
      confirm: 'Yes, exit',
      continue: 'Continue creating',
    },
    datePicker: {
      title: 'Choose a date',
      confirm: 'Done',
    },
    validation: {
      eventName: 'Enter an event name.',
      guests: 'Add at least one guest.',
      customDuration: 'Enter a duration from 1 to 24 hours.',
      eventTime: 'Enter a valid time in HH:MM format.',
    },
    planSuccessTitle: 'Plan created',
    planSuccessMessage: 'The event, calculations, and checklist were saved successfully.',
    planErrorTitle: 'Unable to create plan',
    planErrorMessage: 'Check your internet connection and try again.',
  },
  eventPlan: {
    headerTitle: 'Event plan',
    context: '{adults} adults + {children} children · {duration} hr · {season} · {location}',
    tabs: {
      plan: 'Plan',
      guests: 'Guests',
      shopping: 'Shopping',
      checklist: 'Checklist',
    },
    guests: {
      title: 'Guests',
      invite: 'Invite',
      emptyTitle: 'No guests yet',
      emptyMessage: 'Share the invitation in a chat or show guests its QR code.',
      emptyHint: 'One link or QR code for everyone',
      inviteButton: 'Invite guests',
      total: 'Total',
      accepted: 'Going',
      waiting: 'Waiting',
      declined: 'Declined',
      listTitle: 'Guest list',
      adults: '{count} adults',
      children: '{count} children',
      adultsAndChildren: '{adults} adults + {children} children',
      statusAccepted: 'Confirmed',
      statusMaybe: 'Maybe',
      statusPending: 'Waiting',
      statusDeclined: "Can't go",
      loadError: 'Unable to load guests.',
      retry: 'Try again',
      sheetTitle: 'Invite guests',
      sheetMessage: 'One invitation for everyone — share its link or show the QR code.',
      shareTitle: 'Share invitation',
      shareDescription: 'Send one link to a chat or any messenger',
      qrTitle: 'Show QR code',
      qrDescription: 'Guests scan it with their camera and open the same response form',
      preparing: 'Preparing invitation…',
      invitationErrorTitle: 'Unable to create invitation',
      invitationErrorMessage: 'Check your connection and try again.',
      shareMessage: 'You are invited to “{eventName}”. Respond using this link:',
      qrScreenTitle: 'Invitation QR code',
      qrScreenDescription: 'Show this code to guests. Scanning it opens the response form without installing the app.',
      qrScanHint: 'Scan with the standard phone camera',
      shareInvitation: 'Share invitation',
      copyLink: 'Copy link',
      copiedTitle: 'Link copied',
      copiedMessage: 'You can now send it to your guests.',
      close: 'Close',
    },
    sections: {
      food: 'Recommended food quantities',
      drinks: 'Drinks',
      supplies: 'Supplies',
    },
    categories: {
      snacks_and_canapes: 'Snacks & canapés',
      substantial_food: 'Main food',
      sides_and_vegetables: 'Sides & vegetables',
      fruit_and_dessert: 'Fruit & dessert',
      water: 'Water',
      juice: 'Juice',
      soda: 'Soda',
      beer: 'Beer',
      wine: 'Wine',
      spirits: 'Spirits',
      ice: 'Ice',
      plates: 'Plates',
      cups: 'Cups',
    },
    seasons: { winter: 'winter', spring: 'spring', summer: 'summer', autumn: 'autumn' },
    locations: { indoor: 'indoors', outdoor: 'outdoors' },
    productsNoteTitle: 'You choose the products',
    productsNoteBody: 'The plan sets target quantities but does not choose specific products.',
    unavailableTitle: 'Next section',
    unavailableMessage: 'Shopping and checklist will be connected in the next steps.',
    loadError: 'Unable to load the event plan.',
    retry: 'Try again',
  },
  shopping: {
    title: 'Shopping list',
    progressTitle: 'Shopping progress',
    progress: '{purchased} of {total} purchased',
    groupedView: 'By category',
    listView: 'List',
    allItemsTitle: 'All products',
    emptyTitle: 'Your list is empty',
    emptyBody: 'Add specific products to the calculated categories.',
    targetProgress: 'Planned {planned} of {target} {unit}',
    noItems: 'No products in this category yet.',
    addItem: 'Add product',
    previousItemsTitle: 'Previously added products',
    previousItemsBody: 'They were preserved after recalculation but are no longer linked to a category.',
    itemQuantity: '{quantity} {unit}',
    packageSummary: '{count} × {size} {unit}',
    editItem: 'Edit product',
    deleteItem: 'Delete product',
    completeAction: 'Done',
    undoAction: 'Undo',
    form: {
      addTitle: 'Add product',
      editTitle: 'Edit product',
      category: 'Category',
      name: 'Product name',
      namePlaceholder: 'For example, chicken fillet',
      quantity: 'Total quantity',
      unit: 'Unit',
      packageTitle: 'Packaging — optional',
      packageHint: 'Fill in both fields if the product is sold in packages.',
      packageSize: 'Package size',
      packageCount: 'Number of packages',
      save: 'Save',
      saving: 'Saving…',
      cancel: 'Cancel',
    },
    validation: {
      nameRequired: 'Enter a product name.',
      nameMax: 'The name must be 120 characters or fewer.',
      quantityRequired: 'Enter a quantity.',
      positiveNumber: 'Enter a number greater than zero.',
      packageCountInteger: 'The number of packages must be a whole number.',
      packagePair: 'Enter both package size and package count.',
    },
    deleteConfirmTitle: 'Delete product?',
    deleteConfirmMessage: 'The product will be removed from your shopping list.',
    deleteConfirm: 'Delete',
    loadError: 'Unable to load the shopping list.',
    saveErrorTitle: 'Unable to save product',
    saveErrorMessage: 'Check your internet connection and try again.',
    deleteErrorTitle: 'Unable to delete product',
    deleteErrorMessage: 'Please try again a little later.',
    toggleErrorTitle: 'Unable to update product',
    toggleErrorMessage: 'The purchased state was not saved.',
    retry: 'Try again',
  },
  checklist: {
    title: 'Checklist',
    add: 'Add',
    addTask: 'Add task',
    progressTitle: 'Preparation progress',
    progress: '{completed} of {total} completed',
    remaining: 'Remaining',
    completed: 'Completed',
    emptyTitle: 'No tasks yet',
    emptyBody: 'Add your first task so nothing gets forgotten.',
    markComplete: 'Mark task as completed',
    markIncomplete: 'Move task back to remaining',
    deleteAction: 'Delete',
    completeAction: 'Done',
    undoAction: 'Undo',
    form: {
      addTitle: 'New task',
      editTitle: 'Edit task',
      title: 'Task name',
      placeholder: 'For example, order a cake',
      save: 'Save',
      saving: 'Saving…',
      cancel: 'Cancel',
    },
    validation: {
      titleRequired: 'Enter a task name.',
      titleMax: 'The task name must be 200 characters or fewer.',
    },
    items: {
      confirm_guests: 'Confirm the guest count',
      complete_shopping_list: 'Complete the shopping list',
      buy_products: 'Buy food and drinks',
      chill_drinks: 'Chill the drinks',
      prepare_serving_items: 'Prepare tableware and serving items',
      buy_ice: 'Buy ice',
      set_table: 'Set the table',
      prepare_grill: 'Prepare the grill',
    },
    deleteConfirmTitle: 'Delete task?',
    deleteConfirmMessage: 'The task will be removed from the checklist.',
    loadErrorTitle: 'Unable to refresh checklist',
    loadError: 'Unable to load the checklist.',
    saveErrorTitle: 'Unable to save task',
    saveErrorMessage: 'Check your internet connection and try again.',
    deleteErrorTitle: 'Unable to delete task',
    deleteErrorMessage: 'Please try again a little later.',
    toggleErrorTitle: 'Unable to update task',
    toggleErrorMessage: 'The completion state was not saved.',
    retry: 'Try again',
  },
  eventManagement: {
    actionsLabel: 'Open event actions',
    actionsTitle: 'Manage event',
    generationVersionLabel: 'Generation version',
    generationVersionUnavailable: 'Unavailable',
    editAction: 'Edit event',
    addToCalendar: 'Add to calendar',
    addingToCalendar: 'Opening calendar…',
    calendarSuccessTitle: 'Added to calendar',
    calendarSuccessMessage: 'The event was saved to the selected calendar.',
    calendarErrorTitle: 'Unable to open calendar',
    calendarErrorMessage: 'Check calendar access and try again.',
    deleteAction: 'Delete event',
    cancel: 'Cancel',
    editTitle: 'Edit event',
    saveChanges: 'Save changes',
    savingChanges: 'Saving…',
    loadError: 'Unable to load the event details.',
    retry: 'Try again',
    updateSuccessTitle: 'Event updated',
    updateSuccessMessage: 'Changes were saved and the plan was recalculated.',
    updateErrorTitle: 'Unable to update event',
    updateErrorMessage: 'Check your internet connection and try again.',
    deleteConfirmTitle: 'Delete event?',
    deleteConfirmMessage:
      'The event, plan, shopping list, and checklist will be permanently deleted. This cannot be undone.',
    deleting: 'Deleting…',
    deleteSuccessTitle: 'Event deleted',
    deleteSuccessMessage: 'The event and its related data were deleted.',
    deleteErrorTitle: 'Unable to delete event',
    deleteErrorMessage: 'Please try again a little later.',
    completeAction: 'Complete event',
    reopenAction: 'Reopen event',
    completeTitle: 'How did it go?',
    completeMessage: 'After completion, the event will remain available in your history.',
    incompleteItemsWarning:
      'Shopping items left: {shopping}. Incomplete tasks: {tasks}. You can still complete the event.',
    budgetQuestion: 'Did you stay within the budget?',
    budgetWithin: 'Yes',
    budgetOver: 'No',
    budgetUnknown: 'Not sure',
    completing: 'Completing…',
    completeSuccessTitle: 'Event completed',
    completeSuccessMessage: 'The event was moved to your history.',
    completeErrorTitle: 'Unable to complete event',
    completeErrorMessage: 'Check your connection and try again.',
    reopenSuccessTitle: 'Event reopened',
    reopenSuccessMessage: 'The event can be edited again.',
    reopenErrorTitle: 'Unable to reopen event',
    reopenErrorMessage: 'Check your connection and try again.',
    exit: {
      title: 'Close editing?',
      message: 'Unsaved changes will be lost.',
      confirm: 'Close without saving',
      continue: 'Continue editing',
    },
  },
  profile: {
    back: 'Back',
    title: 'Profile',
    editTitle: 'Edit profile',
    defaultName: 'User',
    emailPlaceholder: 'Email not provided',
    editProfile: 'Edit profile',
    changePhoto: 'Change photo',
    nameLabel: 'Name',
    emailLabel: 'Email',
    save: 'Save',
    saving: 'Saving…',
    settingsSection: 'Settings',
    language: 'Language',
    languageOptions: {
      uk: 'Українська',
      en: 'English',
    },
    theme: 'Theme',
    themeOptions: {
      system: 'System',
      light: 'Light',
      dark: 'Dark',
    },
    settingSaveErrorTitle: 'Unable to change setting',
    settingSaveError: 'Check your connection and try again.',
    accountSection: 'Account',
    changePassword: 'Change password',
    legalSection: 'Legal',
    privacyPolicy: 'Privacy Policy',
    terms: 'Terms',
    deleteAccount: 'Delete account',
    logout: 'Sign out',
    loggingOut: 'Signing out…',
    logoutSuccessTitle: 'Signed out',
    logoutSuccess: 'You have signed out of the current account.',
    logoutErrorTitle: 'Unable to sign out',
    logoutError: 'Please try again.',
    loadErrorTitle: 'Unable to load profile',
    loadError: 'Check your connection and try again.',
    saveSuccessTitle: 'Profile updated',
    saveSuccess: 'Your changes have been saved.',
    saveErrorTitle: 'Unable to save profile',
    saveError: 'Check your details and try again.',
    avatarPermissionTitle: 'Photo access required',
    avatarPermissionError: 'Allow photo access in your device settings.',
    deleteConfirmTitle: 'Delete account?',
    deleteConfirmMessage:
      'This action cannot be undone. All your data and events will be deleted.',
    deleteConfirmAction: 'Yes, delete',
    deleteCancelAction: 'Cancel',
    deletingAccount: 'Deleting…',
    deleteErrorTitle: 'Unable to delete account',
    deleteError: 'Please try again later.',
    privacyPlaceholderTitle: 'Content is being prepared',
    privacyPlaceholderMessage: 'The Privacy Policy will be added before the MVP release.',
    termsPlaceholderTitle: 'Content is being prepared',
    termsPlaceholderMessage: 'The Terms will be added after the final copy is approved.',
    validation: {
      nameRequired: 'Enter your name',
      nameTooLong: 'Name must be 120 characters or fewer',
    },
  },
};
