import type { TranslationSchema } from '@/localization/types';

export const en: TranslationSchema = {
  common: {
    cancel: 'Cancel',
    dismiss: 'Dismiss message',
    socialAuth: {
      continueWithGoogle: 'Continue with Google',
      continueWithApple: 'Continue with Apple',
      googleErrorTitle: 'Unable to sign in with Google',
      appleUnavailableTitle: 'Apple Sign In is not connected yet',
      appleUnavailableMessage: 'Apple Sign In will be added in the next step.',
      errors: {
        providerDisabled: 'Google sign-in is currently unavailable. Please try again later.',
        network: 'Unable to connect. Check your internet connection and try again.',
        invalidCallback: 'Unable to complete sign-in. Please try again.',
        unknown: 'An error occurred while signing in. Please try again.',
      },
    },
  },
  welcome: {
    eyebrow: 'A STRESS-FREE PARTY',
    title: 'Plan your party\nin just a few minutes',
    subtitle:
      "We'll calculate the food, drinks, and shopping — all you need to do is check things off.",
    createAccount: 'Create account',
    existingAccount: 'Already have an account?',
    login: 'Sign in',
    legal: 'By continuing, you agree to the Terms and Privacy Policy',
  },
  login: {
    back: 'Back',
    title: 'Welcome back!',
    subtitle: 'Sign in to continue planning your party.',
    emailLabel: 'Email',
    emailPlaceholder: 'name@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    showPassword: 'Show',
    hidePassword: 'Hide',
    forgotPassword: 'Forgot password?',
    login: 'Sign in',
    loginErrorTitle: 'Unable to sign in',
    loginSuccess: 'You have signed in successfully.',
    loginSuccessTitle: 'Signed in',
    loggingIn: 'Signing in…',
    or: 'or',
    noAccount: "Don't have an account?",
    createAccount: 'Create account',
    securityNote: 'Your data is protected and never shared with third parties',
    errors: {
      invalidCredentials: 'Incorrect email or password.',
      emailNotConfirmed: 'Confirm your email before signing in.',
      rateLimited: 'Too many sign-in attempts. Please try again later.',
      network: 'Unable to connect. Check your internet connection and try again.',
      unknown: 'Unable to sign in. Please try again.',
    },
    validation: {
      emailRequired: 'Enter your email',
      emailInvalid: 'Enter a valid email',
      passwordRequired: 'Enter your password',
    },
  },
  createAccount: {
    back: 'Back',
    title: 'Create account',
    subtitle: 'Start planning parties without the extra stress.',
    nameLabel: 'Name',
    namePlaceholder: 'Your name',
    emailLabel: 'Email',
    emailPlaceholder: 'name@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'At least 8 characters',
    showPassword: 'Show',
    hidePassword: 'Hide',
    submit: 'Create account',
    submitting: 'Creating…',
    or: 'or',
    existingAccount: 'Already have an account?',
    login: 'Sign in',
    legal: 'By registering, you agree to the Terms and Privacy Policy',
    successTitle: 'Account created',
    success: 'Registration is complete.',
    confirmationTitle: 'Confirm your email',
    confirmationMessage: 'We sent you an email with a confirmation link.',
    errorTitle: 'Unable to create account',
    errors: {
      emailAlreadyRegistered: 'An account with this email already exists.',
      invalidEmail: 'Enter a valid email.',
      weakPassword: 'Choose a stronger password.',
      signUpDisabled: 'Registration is currently unavailable.',
      rateLimited: 'Too many attempts. Please try again later.',
      network: 'Unable to connect. Check your internet connection and try again.',
      unknown: 'Unable to create account. Please try again.',
    },
    validation: {
      nameRequired: 'Enter your name',
      nameTooLong: 'Name must be 120 characters or fewer',
      emailRequired: 'Enter your email',
      emailInvalid: 'Enter a valid email',
      passwordRequired: 'Enter a password',
      passwordTooShort: 'Password must be at least 8 characters',
    },
  },
  myEvents: {
    title: 'My events',
    greeting: 'Hi, {name}! All your plans will appear here.',
    defaultName: 'Friend',
    openProfile: 'Open profile',
    emptyTitle: 'Create your first event?',
    emptyBody: "Add guests and a party format — we'll prepare the plan, shopping list, and checklist.",
    createEvent: 'Create event',
    hintTitle: 'A plan in a few minutes',
    hintBody: 'Calculations and lists will be created automatically.',
  },
  createEvent: {
    headerTitle: 'Create event',
    back: 'Back',
    close: 'Close event creation',
    next: 'Next',
    createPlan: 'Create plan',
    step: 'Step {current} of {total}',
    steps: {
      eventType: 'Event type',
      guests: 'Guests',
      details: 'Details',
      menu: 'Menu & drinks',
      review: 'Review',
    },
    eventType: {
      title: 'What are we planning?',
      subtitle: 'Choose a format to help us calculate shopping more accurately.',
      birthday: 'Birthday',
      birthdayHint: 'A festive menu and drinks',
      bbq: 'BBQ / picnic',
      bbqHint: 'Grilling and relaxing outdoors',
      homeParty: 'House party',
      homePartyHint: 'A cozy indoor format',
    },
    guests: {
      title: 'Who is coming?',
      subtitle: 'Enter the guest counts — we will calculate the total automatically.',
      total: 'Total guests',
      breakdown: '{adults} adults · {children} children',
      adults: 'Adults',
      adultsHint: '18 and over',
      children: 'Children',
      childrenHint: 'Under 18',
      alcohol: 'Drink alcohol',
      alcoholHint: 'Maximum {max}',
      validationHint: 'The number of guests drinking alcohol cannot exceed the adult count.',
    },
    details: {
      title: 'When and where?',
      subtitle: 'Add the main event details.',
      name: 'Event name',
      namePlaceholder: "For example, Alina's birthday",
      date: 'Date',
      duration: 'Duration',
      durationHours: '{value} hr',
      other: 'Other',
      customDurationHint: 'From 1 to 24 hours',
      location: 'Location',
      indoor: 'Indoors',
      outdoor: 'Outdoors',
      seasonHint: 'Based on the date: {season} — we will allow for more water and ice.',
      seasons: {
        winter: 'winter',
        spring: 'spring',
        summer: 'summer',
        autumn: 'autumn',
      },
    },
    menu: {
      title: 'What will be served?',
      subtitle: 'Choose the menu format and drink categories.',
      format: 'Menu format',
      snacks: 'Snacks',
      buffet: 'Buffet',
      full: 'Full menu',
      descriptions: {
        snacks: 'Snacks: canapés, finger food, fruit, and a light dessert.',
        buffet: 'Buffet: snacks, canapés, and one main dish.',
        full: 'Full menu: starter, main course, side, and dessert.',
      },
      drinks: 'Drinks',
      beer: 'Beer',
      wine: 'Wine',
      spirits: 'Spirits',
      water: 'Water',
      juice: 'Juice',
      soda: 'Soda',
      waterHint: 'Water is always calculated, regardless of your selection.',
    },
    review: {
      title: 'Review everything',
      subtitle: 'Go back and edit any section if needed.',
      change: 'Edit',
      guestsSummary: '{total} guests',
      drinksSummary: '{menu}. {drinks}',
      budget: 'Budget',
      optional: 'Optional',
      budgetPlaceholder: '8,000',
      currency: '₴',
      note: 'Note',
      notePlaceholder: 'For example, buy the cake separately',
    },
    exit: {
      title: 'Close event creation?',
      message: 'Your unsaved event details will be lost. This action cannot be undone.',
      confirm: 'Yes, exit',
      continue: 'Continue creating',
    },
    datePicker: {
      title: 'Choose a date',
      confirm: 'Done',
    },
    validation: {
      eventName: 'Enter an event name.',
      guests: 'Add at least one guest.',
      customDuration: 'Enter a duration from 1 to 24 hours.',
    },
    planPlaceholderTitle: 'The form is ready',
    planPlaceholderMessage: 'Event saving and plan generation will be connected next.',
  },
  profile: {
    back: 'Back',
    title: 'Profile',
    editTitle: 'Edit profile',
    defaultName: 'User',
    emailPlaceholder: 'Email not provided',
    editProfile: 'Edit profile',
    changePhoto: 'Change photo',
    nameLabel: 'Name',
    emailLabel: 'Email',
    save: 'Save',
    saving: 'Saving…',
    settingsSection: 'Settings',
    language: 'Language',
    languageOptions: {
      uk: 'Українська',
      en: 'English',
    },
    theme: 'Theme',
    themeOptions: {
      system: 'System',
      light: 'Light',
      dark: 'Dark',
    },
    settingSaveErrorTitle: 'Unable to change setting',
    settingSaveError: 'Check your connection and try again.',
    accountSection: 'Account',
    changePassword: 'Change password',
    legalSection: 'Legal',
    privacyPolicy: 'Privacy Policy',
    terms: 'Terms',
    deleteAccount: 'Delete account',
    logout: 'Sign out',
    loggingOut: 'Signing out…',
    logoutSuccessTitle: 'Signed out',
    logoutSuccess: 'You have signed out of the current account.',
    logoutErrorTitle: 'Unable to sign out',
    logoutError: 'Please try again.',
    loadErrorTitle: 'Unable to load profile',
    loadError: 'Check your connection and try again.',
    saveSuccessTitle: 'Profile updated',
    saveSuccess: 'Your changes have been saved.',
    saveErrorTitle: 'Unable to save profile',
    saveError: 'Check your details and try again.',
    avatarPermissionTitle: 'Photo access required',
    avatarPermissionError: 'Allow photo access in your device settings.',
    unavailableTitle: 'Coming soon',
    unavailableMessage: 'This setting will be available in a future update.',
    deleteConfirmTitle: 'Delete account?',
    deleteConfirmMessage:
      'This action cannot be undone. All your data and events will be deleted.',
    deleteConfirmAction: 'Yes, delete',
    deleteCancelAction: 'Cancel',
    deletingAccount: 'Deleting…',
    deleteErrorTitle: 'Unable to delete account',
    deleteError: 'Please try again later.',
    privacyPlaceholderTitle: 'Content is being prepared',
    privacyPlaceholderMessage: 'The Privacy Policy will be added before the MVP release.',
    termsPlaceholderTitle: 'Content is being prepared',
    termsPlaceholderMessage: 'The Terms will be added after the final copy is approved.',
    validation: {
      nameRequired: 'Enter your name',
      nameTooLong: 'Name must be 120 characters or fewer',
    },
  },
};
