import type { TranslationSchema } from '@/localization/types';

export const uk: TranslationSchema = {
  common: {
    cancel: 'Скасувати',
    dismiss: 'Закрити повідомлення',
    socialAuth: {
      continueWithGoogle: 'Продовжити з Google',
      continueWithApple: 'Продовжити з Apple',
      googleErrorTitle: 'Не вдалося увійти через Google',
      appleUnavailableTitle: 'Apple Sign In ще не підключено',
      appleUnavailableMessage: 'Додамо вхід через Apple наступним кроком.',
      errors: {
        providerDisabled: 'Вхід через Google зараз недоступний. Спробуйте пізніше.',
        network: 'Не вдалося підключитися. Перевірте інтернет і спробуйте ще раз.',
        invalidCallback: 'Не вдалося завершити авторизацію. Спробуйте ще раз.',
        unknown: 'Сталася помилка під час входу. Спробуйте ще раз.',
      },
    },
  },
  welcome: {
    eyebrow: 'ВЕЧІРКА БЕЗ СТРЕСУ',
    title: 'Сплануй вечірку\nза кілька хвилин',
    subtitle:
      'Розрахуємо їжу, напої та покупки — тобі залишиться лише відмічати готове.',
    createAccount: 'Створити акаунт',
    existingAccount: 'Вже є акаунт?',
    login: 'Увійти',
    legal: 'Продовжуючи, ти погоджуєшся з Умовами та Політикою конфіденційності',
  },
  login: {
    back: 'Назад',
    title: 'З поверненням!',
    subtitle: 'Увійди, щоб продовжити планування вечірки.',
    emailLabel: 'Email',
    emailPlaceholder: 'name@example.com',
    passwordLabel: 'Пароль',
    passwordPlaceholder: 'Введіть пароль',
    showPassword: 'Показати',
    hidePassword: 'Сховати',
    forgotPassword: 'Забули пароль?',
    login: 'Увійти',
    loginErrorTitle: 'Не вдалося увійти',
    loginSuccess: 'Ви успішно увійшли.',
    loginSuccessTitle: 'Вхід виконано',
    loggingIn: 'Входимо…',
    or: 'або',
    noAccount: 'Немає акаунта?',
    createAccount: 'Створити акаунт',
    securityNote: 'Твої дані захищені та не передаються третім особам',
    errors: {
      invalidCredentials: 'Неправильний email або пароль.',
      emailNotConfirmed: 'Підтвердіть email перед входом.',
      rateLimited: 'Забагато спроб входу. Спробуйте трохи пізніше.',
      network: 'Не вдалося підключитися. Перевірте інтернет і спробуйте ще раз.',
      unknown: 'Не вдалося увійти. Спробуйте ще раз.',
    },
    validation: {
      emailRequired: 'Введіть email',
      emailInvalid: 'Введіть коректний email',
      passwordRequired: 'Введіть пароль',
    },
  },
  createAccount: {
    back: 'Назад',
    title: 'Створити акаунт',
    subtitle: 'Почни планувати вечірки без зайвого стресу.',
    nameLabel: 'Ім’я',
    namePlaceholder: 'Ваше ім’я',
    emailLabel: 'Email',
    emailPlaceholder: 'name@example.com',
    passwordLabel: 'Пароль',
    passwordPlaceholder: 'Мінімум 8 символів',
    showPassword: 'Показати',
    hidePassword: 'Сховати',
    submit: 'Створити акаунт',
    submitting: 'Створюємо…',
    or: 'або',
    existingAccount: 'Вже є акаунт?',
    login: 'Увійти',
    legal: 'Реєструючись, ти погоджуєшся з Умовами та Політикою конфіденційності',
    successTitle: 'Акаунт створено',
    success: 'Реєстрацію завершено.',
    confirmationTitle: 'Підтвердьте email',
    confirmationMessage: 'Ми надіслали лист із посиланням для підтвердження.',
    errorTitle: 'Не вдалося створити акаунт',
    errors: {
      emailAlreadyRegistered: 'Акаунт із таким email уже існує.',
      invalidEmail: 'Введіть коректний email.',
      weakPassword: 'Оберіть надійніший пароль.',
      signUpDisabled: 'Реєстрація зараз недоступна.',
      rateLimited: 'Забагато спроб. Спробуйте трохи пізніше.',
      network: 'Не вдалося підключитися. Перевірте інтернет і спробуйте ще раз.',
      unknown: 'Не вдалося створити акаунт. Спробуйте ще раз.',
    },
    validation: {
      nameRequired: 'Введіть ім’я',
      nameTooLong: 'Ім’я може містити не більше 120 символів',
      emailRequired: 'Введіть email',
      emailInvalid: 'Введіть коректний email',
      passwordRequired: 'Введіть пароль',
      passwordTooShort: 'Пароль має містити щонайменше 8 символів',
    },
  },
  myEvents: {
    title: 'Мої події',
    greeting: 'Привіт, {name}! Тут з’являться всі твої плани.',
    defaultName: 'Друже',
    openProfile: 'Відкрити профіль',
    emptyTitle: 'Створимо першу подію?',
    emptyBody: 'Додай гостей і формат вечірки — ми підготуємо план, покупки та чекліст.',
    createEvent: 'Створити подію',
    hintTitle: 'План за кілька хвилин',
    hintBody: 'Розрахунки й списки створяться автоматично.',
  },
  profile: {
    back: 'Назад',
    title: 'Профіль',
    editTitle: 'Редагувати профіль',
    defaultName: 'Користувач',
    emailPlaceholder: 'Email не вказано',
    editProfile: 'Редагувати профіль',
    changePhoto: 'Змінити фото',
    nameLabel: 'Ім’я',
    emailLabel: 'Email',
    save: 'Зберегти',
    saving: 'Зберігаємо…',
    settingsSection: 'Налаштування',
    language: 'Мова',
    languageOptions: {
      uk: 'Українська',
      en: 'English',
    },
    theme: 'Тема',
    themeOptions: {
      system: 'Системна',
      light: 'Світла',
      dark: 'Темна',
    },
    settingSaveErrorTitle: 'Не вдалося змінити налаштування',
    settingSaveError: 'Перевірте інтернет і спробуйте ще раз.',
    accountSection: 'Акаунт',
    changePassword: 'Змінити пароль',
    legalSection: 'Правова інформація',
    privacyPolicy: 'Privacy Policy',
    terms: 'Terms',
    deleteAccount: 'Видалити акаунт',
    logout: 'Вийти',
    loggingOut: 'Виходимо…',
    logoutSuccessTitle: 'Вихід виконано',
    logoutSuccess: 'Ви вийшли з поточного акаунта.',
    logoutErrorTitle: 'Не вдалося вийти',
    logoutError: 'Спробуйте ще раз.',
    loadErrorTitle: 'Не вдалося завантажити профіль',
    loadError: 'Перевірте інтернет і спробуйте ще раз.',
    saveSuccessTitle: 'Профіль оновлено',
    saveSuccess: 'Зміни успішно збережено.',
    saveErrorTitle: 'Не вдалося зберегти профіль',
    saveError: 'Перевірте дані та спробуйте ще раз.',
    avatarPermissionTitle: 'Потрібен доступ до фото',
    avatarPermissionError: 'Дозвольте доступ до фотографій у налаштуваннях пристрою.',
    unavailableTitle: 'Ще не готово',
    unavailableMessage: 'Це налаштування з’явиться в одному з наступних оновлень.',
    deleteConfirmTitle: 'Видалити акаунт?',
    deleteConfirmMessage:
      'Цю дію неможливо скасувати. Усі ваші дані та події буде видалено.',
    deleteConfirmAction: 'Так, видалити',
    deleteCancelAction: 'Скасувати',
    deletingAccount: 'Видаляємо…',
    deleteErrorTitle: 'Не вдалося видалити акаунт',
    deleteError: 'Спробуйте ще раз трохи пізніше.',
    privacyPlaceholderTitle: 'Текст готується',
    privacyPlaceholderMessage:
      'Політика конфіденційності буде додана до публікації MVP.',
    termsPlaceholderTitle: 'Текст готується',
    termsPlaceholderMessage:
      'Умови використання буде додано після погодження фінального тексту.',
    validation: {
      nameRequired: 'Введіть ім’я',
      nameTooLong: 'Ім’я може містити не більше 120 символів',
    },
  },
};
