import { StyleSheet } from 'react-native';

import type { AppTheme } from '@/hooks/app-theme';

export function createEventGuestsStyles(
  theme: AppTheme,
  bottomInset: number,
  topInset = 0,
) {
  const { colors, spacing, typography } = theme;

  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.background.canvas },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: spacing.x5,
      paddingTop: spacing.x4,
      paddingBottom: bottomInset,
    },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    title: { ...typography.heading3, color: colors.text.primary },
    inviteAction: { flexDirection: 'row', alignItems: 'center', gap: spacing.x1, paddingVertical: spacing.x2 },
    inviteActionText: { ...typography.labelLarge, color: colors.text.brand },
    empty: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: spacing.x4, paddingVertical: spacing.x12 },
    emptyIcon: {
      width: 120,
      height: 120,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 60,
      backgroundColor: colors.background.subtle,
    },
    emptyTitle: { ...typography.titleLarge, color: colors.text.primary, textAlign: 'center' },
    emptyMessage: { ...typography.bodySmall, maxWidth: 320, color: colors.text.secondary, textAlign: 'center' },
    emptyHint: {
      width: '100%',
      padding: spacing.x3,
      borderRadius: spacing.x4,
      backgroundColor: colors.background.subtle,
    },
    emptyHintText: { ...typography.bodySmall, color: colors.text.brand, textAlign: 'center' },
    emptyButton: { width: '82%' },
    summary: {
      flexDirection: 'row',
      marginTop: spacing.x4,
      paddingVertical: spacing.x4,
      borderRadius: spacing.x4,
      backgroundColor: colors.background.subtle,
    },
    summaryItem: { flex: 1, alignItems: 'center', gap: spacing.x1 },
    summaryValue: { ...typography.titleMedium, color: colors.text.primary },
    summaryLabel: { ...typography.caption, color: colors.text.secondary },
    listTitle: { ...typography.titleMedium, marginTop: spacing.x6, marginBottom: spacing.x3, color: colors.text.primary },
    guestList: { gap: spacing.x3 },
    guestCard: {
      gap: spacing.x3,
      padding: spacing.x4,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x4,
      backgroundColor: colors.background.surface,
    },
    guestHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.x3 },
    guestDot: { width: spacing.x2, height: spacing.x2, marginTop: spacing.x2, borderRadius: spacing.x1 },
    guestCopy: { flex: 1, gap: spacing.x1 },
    guestName: { ...typography.labelLarge, color: colors.text.primary },
    guestPeople: { ...typography.bodySmall, color: colors.text.secondary },
    accountBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: spacing.x1,
      marginTop: spacing.x1,
      paddingHorizontal: spacing.x2,
      paddingVertical: spacing.x1,
      borderRadius: spacing.x3,
    },
    accountBadgeApp: { backgroundColor: colors.background.subtle },
    accountBadgeLink: { backgroundColor: colors.background.canvas },
    accountBadgeText: { ...typography.caption },
    accountBadgeTextApp: { color: colors.text.brand },
    accountBadgeTextLink: { color: colors.text.secondary },
    statusPill: { paddingHorizontal: spacing.x3, paddingVertical: spacing.x1, borderRadius: spacing.x4 },
    statusText: { ...typography.labelSmall },
    state: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: spacing.x4, padding: spacing.x6 },
    stateText: { ...typography.bodyMedium, color: colors.text.secondary, textAlign: 'center' },
    retryButton: { width: 220 },
    modalRoot: { flex: 1, justifyContent: 'flex-end' },
    backdrop: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(20, 24, 33, 0.48)' },
    backdropPressable: { flex: 1 },
    sheet: {
      gap: spacing.x3,
      paddingTop: spacing.x3,
      paddingHorizontal: spacing.x6,
      paddingBottom: Math.max(bottomInset, spacing.x6),
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      backgroundColor: colors.background.surface,
    },
    handle: { width: spacing.x12, height: spacing.x1, alignSelf: 'center', borderRadius: spacing.x1, backgroundColor: colors.border.strong },
    sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.x3 },
    sheetTitle: { ...typography.titleLarge, color: colors.text.primary },
    closeButton: { width: spacing.x8, height: spacing.x8, alignItems: 'center', justifyContent: 'center' },
    sheetMessage: { ...typography.bodySmall, color: colors.text.secondary },
    option: {
      minHeight: 82,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.x3,
      padding: spacing.x3,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: spacing.x4,
      backgroundColor: colors.background.surface,
    },
    optionPrimary: { borderColor: colors.border.brand, backgroundColor: colors.background.subtle },
    optionAccent: { borderColor: colors.background.accent, backgroundColor: colors.background.accentSubtle },
    optionIcon: { width: spacing.x10, height: spacing.x10, alignItems: 'center', justifyContent: 'center', borderRadius: spacing.x5, backgroundColor: colors.background.surface },
    optionCopy: { flex: 1, gap: spacing.x1 },
    optionTitle: { ...typography.labelLarge, color: colors.text.primary },
    optionDescription: { ...typography.caption, color: colors.text.secondary },
    optionDisabled: { opacity: 0.55 },
    note: { padding: spacing.x3, borderRadius: spacing.x3, backgroundColor: colors.background.subtle },
    noteText: { ...typography.caption, color: colors.text.brand },
    qrScreen: { flex: 1, backgroundColor: colors.background.canvas },
    qrHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: topInset + spacing.x3,
      paddingBottom: spacing.x3,
      paddingHorizontal: spacing.x5,
    },
    qrHeaderTitle: { ...typography.titleMedium, color: colors.text.primary },
    qrContent: { flex: 1, gap: spacing.x5, paddingHorizontal: spacing.x5, paddingBottom: Math.max(bottomInset, spacing.x6) },
    qrTitle: { ...typography.heading3, color: colors.text.primary },
    qrDescription: { ...typography.bodySmall, color: colors.text.secondary },
    qrCard: { alignSelf: 'center', padding: spacing.x6, borderWidth: 1, borderColor: colors.border.default, borderRadius: spacing.x6, backgroundColor: '#FFFFFF' },
    qrHint: { ...typography.bodySmall, color: colors.text.secondary, textAlign: 'center' },
    qrActions: { gap: spacing.x3, marginTop: spacing.x3 },
    qrNote: { marginTop: 'auto', padding: spacing.x4, borderRadius: spacing.x4, backgroundColor: colors.background.accentSubtle },
    qrNoteText: { ...typography.bodySmall, color: colors.background.accent },
  });
}
